name: robodogs
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.3.1=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - brotli-python=1.2.0=py310haaa1140_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py310hf5b66c1_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py310h7b404bc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - docstring_parser=0.17.0=pyhd8ed1ab_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - farama-notifications=0.0.4=pyhd8ed1ab_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - grpcio=1.74.1=py310h1e75bc9_1
  - gymnasium=1.2.1=np2py310hcd98a52_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.0.0=pyh5552912_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jax-jumpy=1.0.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libblas=3.9.0=38_h51639a9_openblas
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcxx=21.1.3=hf598326_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libgrpc=1.74.1=h3063b79_1
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_ha158390_2
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h658db43_2
  - libre2-11=2025.08.12=h91c62da_1
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=h4237e3c_0
  - libtiff=4.7.1=h7dc4979_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.4=h4a912ad_0
  - markdown=3.9=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310hf4fd40f_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.2.6=py310h4d83441_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.5.4=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - protobuf=6.31.1=py310hc33aa15_2
  - psutil=7.1.0=py310hfe3a0ae_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.3=pyh3cfb1c2_0
  - pydantic-core=2.41.4=py310hf3301a5_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h14e4db3_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pyyaml=6.0.3=py310hf4fd40f_0
  - pyzmq=27.1.0=py310hc4a7dca_0
  - re2=2025.08.12=h64b956e_1
  - readline=8.2=h1d1bf99_2
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - sentry-sdk=2.43.0=pyhd8ed1ab_0
  - setproctitle=1.3.6=py310h7bdd564_1
  - setuptools=80.9.0=pyhff2d567_0
  - shtab=1.7.2=pyhd8ed1ab_0
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py310h0305fc1_3
  - tk=8.6.13=h892fb3f_2
  - tornado=6.5.2=py310h7bdd564_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typeguard=4.4.4=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tyro=0.9.35=pyhd8ed1ab_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wandb=0.22.3=py310h53169e7_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=hf787086_0
  - zstandard=0.25.0=py310hf151d32_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - contourpy==1.3.2
      - cycler==0.12.1
      - etils==1.13.0
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - glfw==2.10.0
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - moviepy==2.2.1
      - mpmath==1.3.0
      - mujoco==3.3.7
      - networkx==3.4.2
      - opencv-python==4.12.0.88
      - pandas==2.3.3
      - pillow==11.3.0
      - proglog==0.1.12
      - pygame==2.6.1
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - pytz==2025.2
      - seaborn==0.13.2
      - sympy==1.14.0
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - tqdm==4.67.1
      - tzdata==2025.2
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/robodogs
