name: robodogs
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.3.1=pyhd8ed1ab_0
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.4.0=pyh71513ae_0
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=h7dd00d9_1
  - brax=0.12.5=pyhd8ed1ab_0
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - chex=0.1.90=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310h7f4e7e6_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.8.17=py310h7b404bc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dm-env=1.6=pyhd8ed1ab_1
  - dm-tree=0.1.9=py310h7fed476_1
  - etils=1.12.2=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - flask=3.1.2=pyhd8ed1ab_0
  - flask-cors=6.0.1=pyhe01879c_0
  - flax=0.10.2=pyhd8ed1ab_0
  - fonttools=4.60.1=py310hf4fd40f_0
  - freetype=2.14.1=hce30654_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - glfw=3.4=hc919400_1
  - grpcio=1.71.0=py310h1273d39_1
  - gym=0.26.1=py310hbe9552e_0
  - gym-notices=0.1.0=pyhe01879c_0
  - humanize=4.13.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=7.0.0=pyh5552912_0
  - ipython=8.37.0=pyh8f84b5b_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jax=0.6.2=pyhd8ed1ab_0
  - jaxlib=0.6.2=cpu_py310h2ee8168_1
  - jaxopt=0.8.4=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - kiwisolver=1.4.9=py310h92dc006_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250127.1=cxx17_h07bc746_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.9.0=37_h51639a9_openblas
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcblas=3.9.0=37_hb0561ab_openblas
  - libccd-double=2.1=h9a09cb3_2
  - libcurl=8.14.1=h73640d1_0
  - libcxx=21.1.3=hf598326_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libgrpc=1.71.0=h857da87_1
  - libiconv=1.18=h23cfdf5_2
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=37_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libmujoco=3.3.2=hf878f1f_2
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.30=openmp_h60d53f8_2
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=5.29.3=h6c9c1dd_2
  - libre2-11=2025.06.26=hd41c47c_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h7dc4979_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.0=h9329255_1
  - libxml2-16=2.15.0=h0ff4647_1
  - libxslt=1.1.43=hb2570ba_1
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.3=h4a912ad_0
  - lodepng=20220109=hf86a087_0
  - lxml=6.0.2=py310hca4a255_1
  - lz4-c=1.10.0=h286801f_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py310hf4fd40f_0
  - matplotlib-base=3.10.6=py310h0181960_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - ml-collections=1.0.0=pyh29332c3_0
  - ml_dtypes=0.5.1=py310h03dc5a2_1
  - msgpack-python=1.1.2=py310h0e897d2_0
  - mujoco-mjx=3.3.2=pyhd8ed1ab_0
  - mujoco-python=3.3.2=np2py310h0434d20_2
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.5.4=h5503f6c_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optax=0.2.6=pyhd8ed1ab_0
  - orbax-checkpoint=0.8.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - playground=0.0.3=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - protobuf=5.29.3=py310h75f3243_0
  - psutil=7.1.0=py310hfe3a0ae_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=4=hd8ed1ab_3
  - pyglfw=2.10.0=pyha770c72_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyopengl=3.1.10=pyh534df25_2
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.10.19=h14e4db3_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pytinyrenderer=0.0.13=py310h50276c9_3
  - pyyaml=6.0.3=py310hf4fd40f_0
  - pyzmq=27.1.0=py310hc4a7dca_0
  - qhull=2020.2=h420ef59_5
  - rav1e=0.7.1=h0716509_3
  - re2=2025.06.26=h6589ca4_0
  - readline=8.2=h1d1bf99_2
  - rich=14.2.0=pyhcf101f3_0
  - scipy=1.15.2=py310h32ab4ed_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=hd121638_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.1.2=h12ba402_0
  - tensorboardx=2.6.2.2=pyhd8ed1ab_1
  - tensorstore=0.1.65=py310h2bd4c24_5
  - tinyxml2=11.0.0=ha1acc90_0
  - tk=8.6.13=h892fb3f_2
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.2=py310h7bdd564_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trimesh=4.8.3=pyh7b2049a_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py310h7bdd564_1
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - wrapt=1.17.3=py310h7bdd564_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h888dc83_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - farama-notifications==0.0.4
      - filelock==3.20.0
      - gymnasium==1.2.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - pillow==12.0.0
      - sympy==1.14.0
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
